name = "mock-api"
type = "webpack"

account_id = "d386dce443b620e59942b0e38c9679ee"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2021-10-07"


kv_namespaces = [ 
  { binding = "KV", id = "f1b6bf1bf23e451da4fdac5b8c22d076",  preview_id = "6a8ad7d41e0b48f083889a89d3084051" }
]

#[triggers]
#crons = ["* * * * *"]